KS-2-3 Task about train
kiwitaste/KotlinSprint pull request #11
Opened 2024-10-04 14:35 UTC by kiwitaste

2024-10-05 05:29 UTC, ievetrovdev requested changes

2024-10-05 05:29 UTC, ievetrovdev commented on src/main/kotlin/sprintlesson_2/lesson2_task3.kt
> +    val departureTimeHour = 9 * 60 // преобразую часы в минуты, вопрос как лучше назвать переменную в таком случае?
Все окей, но чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это магическое число, что тоже не является хорошей практикой.
Точных правил нет, только было бы понятно другим читателям и тебе самому, если зайти спустя несколько месяцев)
в данном случае лучше сначала объявить просто значение, а преобразование в минуты сделать уже в отдельную переменную

2024-10-07 17:32 UTC, kiwitaste commented on src/main/kotlin/sprintlesson_2/lesson2_task3.kt
> +    val departureTimeHour = 9 * 60 // преобразую часы в минуты, вопрос как лучше назвать переменную в таком случае?
Привет!
Сделано.
1. Вынесла в константу. Если я верно помню, то надо писать ее капсом. Так?
Но не помню в каком уроке это было. Либо я просто нагуглила :)
2. Добавила новую переменную для указания часов.
3. Переименовала переменную, где перевожу часы в минуты, чтобы было понятно что это.

2024-10-08 07:13 UTC, ievetrovdev approved these changes
Да все верно. Переменная тоже хорошо названа

2024-10-08 08:07 UTC, merged