KS 4-2 Task about cargo
kiwitaste/KotlinSprint pull request #18
Opened 2024-10-10 07:43 UTC by kiwitaste

2024-10-10 13:25 UTC, ievetrovdev requested changes

2024-10-10 13:25 UTC, ievetrovdev commented on src/main/kotlin/sprintlesson_4/lesson4_task2.kt
> +    val volumeMax = 100
предлагаю переменные с которыми сравниваем входные данные вынести в константы, так как они точно не будут меняться после компиляции

2024-10-10 18:08 UTC, kiwitaste commented on src/main/kotlin/sprintlesson_4/lesson4_task2.kt
> +    val volumeMax = 100
Точно, спасибо!

2024-10-11 07:32 UTC, ievetrovdev approved these changes

2024-10-11 11:13 UTC, merged