KS 4-3 Task about plants
kiwitaste/KotlinSprint pull request #19
Opened 2024-10-10 08:12 UTC by kiwitaste

2024-10-10 13:27 UTC, ievetrovdev requested changes

2024-10-10 13:27 UTC, ievetrovdev commented on src/main/kotlin/sprintlesson_4/lesson4_task3.kt
> +    println("Благоприятные ли условия сейчас для роста бобовых? ${sunnyWetter && openTent && humidity == 20 && yearSeason != "зима"}")
Значения в этом коде являются магическими числами. Не лучшая практика. Предлагаю добавить переменные) Согласно условию следует проинициализировать значения с которыми сравниваются критерии) их, кстати, стоит вынести в константы, так как они постоянные и не планируются изменяться после компиляции.

2024-10-10 13:27 UTC, ievetrovdev commented on src/main/kotlin/sprintlesson_4/lesson4_task3.kt
> +    val sunnyWetter: Boolean = true
Лучше использовать более релевантное название. В данном случае для Boolean переменной, которая является своеобразным "флагом" состояния. И для них рекомендуемая конструкция такая: isSunny / isAwningOpen

2024-10-10 18:29 UTC, kiwitaste commented on src/main/kotlin/sprintlesson_4/lesson4_task3.kt
> +    val sunnyWetter: Boolean = true
Ок, поменяла

2024-10-10 18:51 UTC, kiwitaste commented on src/main/kotlin/sprintlesson_4/lesson4_task3.kt
> +    println("Благоприятные ли условия сейчас для роста бобовых? ${sunnyWetter && openTent && humidity == 20 && yearSeason != "зима"}")
Если верно поняла, то в константы надо было вынести 20 и "зима".

2024-10-11 07:34 UTC, ievetrovdev approved these changes

2024-10-11 07:34 UTC, ievetrovdev commented on src/main/kotlin/sprintlesson_4/lesson4_task3.kt
> +const val WRONG_SEASON: String = "зима"
вообще булевы значения для условия тоже можно было вывести в константы

2024-10-11 11:13 UTC, merged