SprintLesson-1 Solution for the task 1 - created two variables
kiwitaste/KotlinSprint pull request #4
Opened 2024-10-02 10:15 UTC by kiwitaste

2024-10-02 10:39 UTC, kiwitaste commented
Привет, Иван! 
Почему-то в этом пулл-реквесте два файла (за 1 и 2 таски), хотя я отправляла только второй файл для таска 2.
Подскажи, почему так получилось? Это потому что 1 таск еще не проверен и не вмерджен в main? Он еще на проверке.

2024-10-02 13:55 UTC, ievetrovdev requested changes
Привет. Так получилось потому что второе задание ты так же сделала в этой же ветке. 

Новые ветки создаем только из мастера (который предварительно надо обновить, если до этого мержились задачи в гитхабе), чтобы не было пересечений с другими тасками)

Что делать?
в данном пулл реквесте надо:
- переключиться в ветку текущего ПР
- удалить лишний файл с задачей (физически из проекта)
- сделать коммит (с изменением удаления)
- прислать ссылку на этот же пулл реквест снова в бот
И новые ветки всегда создаем из основной ветки master.

По оформлению пулл реквеста:
 - Префикс проекта с названием и номером урока задачи следует прописывать в названии пулл реквеста. Например, "KS-1-1 сделал то-то".
 - Название ветки также должно содержать префикс проекта с номером урока и задачи, чтобы они все были уникальны и в них можно было легко ориентироваться. Слова в названии веток разделяются дефисами. Не используем кириллицу. Например, “KS-1-1-create-smth”.

2024-10-02 13:57 UTC, ievetrovdev requested changes

2024-10-02 13:57 UTC, ievetrovdev commented on src/main/kotlin/sprintlesson_1/sprintlesson1_task1.kt
> +val notificationAboutPurchase = "Спасибо за покупку!"
В IDEA есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx). Рекомендую взять в привычку прожимать автоформат всегда перед коммитом, чтобы все отступы и пробелы расставить по своим местам.

2024-10-02 13:57 UTC, ievetrovdev commented on src/main/kotlin/sprintlesson_1/sprintlesson1_task2.kt
> +    val numberOfOrders = 75
Этот файл нужно будет убрать из этой ветки, и добавить в новую ветку. После этого заданого отправить ссылку на новый ПР

2024-10-02 14:27 UTC, kiwitaste commented on src/main/kotlin/sprintlesson_1/sprintlesson1_task1.kt
> +val notificationAboutPurchase = "Спасибо за покупку!"
Спасибо, сделаю!

2024-10-02 14:31 UTC, kiwitaste commented on src/main/kotlin/sprintlesson_1/sprintlesson1_task2.kt
> +    val numberOfOrders = 75
Ok

2024-10-03 07:54 UTC, ievetrovdev approved these changes

2024-10-03 14:53 UTC, closed without merging