KS-1-4 Added println for each val
kiwitaste/KotlinSprint pull request #7
Opened 2024-10-03 09:07 UTC by kiwitaste

Иван, привет!

В прошлом коммите был неверный номер 1-3, исправила на 1-4.
Также добавила вывод каждой переменной.

**Вопрос 1:** почему расстояние указано с нижними подчеркиваниями 40_868_600_000?
Можно ли было указывать без них просто как число 40868600000?

**Вопрос 2:** если я пытаюсь делать **Run** через шорткат (control + R), всегда раннится предыдущий запускаемый файл. То есть надо именно мышкой наводить на play и тогда запустится текущий файл.
Как сделать так, чтобы сразу по шорткату запускать текущий файл, который еще ни разу не запускался?

2024-10-03 09:10 UTC, kiwitaste commented
**Вопрос 3:** Надо ли после аппрува пул-реквестов мерждить каждую вертку в main?

2024-10-03 14:25 UTC, ievetrovdev requested changes

2024-10-03 14:25 UTC, ievetrovdev commented on src/main/kotlin/sprintlesson_1/lesson1_task4.kt
> +    val partOfDay: Double = 0.075
Полагаю есть еще меньше дробный тип, чем Double)

2024-10-03 14:25 UTC, ievetrovdev commented on src/main/kotlin/sprintlesson_1/lesson1_task4.kt
> +    val seconds: Int = 6480
Тут тоже

2024-10-03 14:27 UTC, ievetrovdev commented
1. Нет не обязательно, просто чуть удобнее читать
2. Често пока затрудняюсь ответить
3. Да, такой рабочий процесс

2024-10-03 14:41 UTC, kiwitaste commented on src/main/kotlin/sprintlesson_1/lesson1_task4.kt
> +    val seconds: Int = 6480
Это один и тот же файл. Либо я не поняла, где именно во втором случае надо сменить тип?
В val partOfDay поменяла Double на Float и в конце добавила f.
Верно?

А что насчет val partOfYear?
Должно быть тоже Float = 2.0547945205479453E-4f
Тогда идея пишет, что надо запись сократить. Или все же там Double верно записано?

2024-10-04 07:00 UTC, ievetrovdev requested changes

2024-10-04 07:00 UTC, ievetrovdev commented on src/main/kotlin/sprintlesson_1/lesson1_task4.kt
> +    val seconds: Int = 6480
c float и double все верно,
с seconds int слишком большой  можно заменить на Short
тут их диапазоны https://kotlinlang.ru/docs/basic-types.html

2024-10-04 14:42 UTC, kiwitaste commented on src/main/kotlin/sprintlesson_1/lesson1_task4.kt
> +    val seconds: Int = 6480
Поняла, спасибо

2024-10-05 05:32 UTC, ievetrovdev approved these changes

2024-10-07 10:02 UTC, merged